TERMUX_PKG_HOMEPAGE=https://developers.yubico.com/libfido2/
TERMUX_PKG_DESCRIPTION="Library functionality for FIDO 2.0"
TERMUX_PKG_LICENSE="BSD-2-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.15.0
TERMUX_PKG_SRCURL=https://developers.yubico.com/libfido2/Releases/libfido2-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=abaab1318d21d262ece416fb8a7132fa9374bda89f6fa52b86a98a2f5712b61e
TERMUX_PKG_DEPENDS="hidapi, libcbor, openssl, termux-api, zlib"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_EXAMPLES=OFF 
-DBUILD_STATIC_LIBS=OFF
-DUSE_HIDAPI=ON
-DHIDAPI_SUFFIX=-libusb
"
